export type Client = {
    caravana: number;
    nomeCaravana: string;
    cidade: string;
    dataEntrada: string;
    dataNascimento: string;
    dataSaida: string;
    documento: string;
    email: string;
    estado: string;
    genero: 'Masculino' | 'Feminino';
    id: number;
    nacionalidade: string;
    nome: string;
    telefone: string;
    guia: number;
    nomeGuia: string;
    evento: string;
    leito: number;
};
